version: '3.1'

# https://docs.docker.com/compose/compose-file/
# For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  # Nginx for reverse proxying data
  http:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:${NOTIFIER_HTTP_PORT:-80}
      - 443:${NOTIFIER_HTTPS_PORT:-443}
    depends_on: 
      - backend
  # Admin web interface
  admin:
    build:
      context: .
      dockerfile: ./packages/admin/Dockerfile
      args:
        - API_URL=http://backend:8085/
    depends_on:
      - backend
    expose:
      - 3000:3000
  # Bot itself and REST api
  backend:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    depends_on:
      db:
         condition: service_healthy
    volumes:
      - db-data:/run/backend-data
      - backend-settings:/run/server-settings
    environment:
      - NOTIFIER_SETTINGS_FILENAME=/run/server-settings/settings.json
      - DB_FILE=/run/backend-data/database.sqlite
    expose:
      - 3001:3001
    healthcheck:
      test: [ "curl", "http://localhost:3001/" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
  backend-settings:
