version: '3.1'
include:
  - compose.yml
services:
  http:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      # TODO volumes for certificates?.. Cert files?
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - backend